---
Name: delectus-index-config
After:
  - 'delectus/*'
---
Injector:
  DelectusIndexModule:
    class: DelectusIndexModule
  DelectusIndexService:
    class: DelectusIndexService
    properties:
      module: %$DelectusIndexModule
DelectusIndexModule:
  version: 'v1'
DelectusTransport:
  endpoints:
    index: 'https://api.delectus.io/'
