---
Name: delectus-index-config
After:
  - 'delectus/*'
---
Injector:
  DelectusIndexService:
    class: DelectusIndexService
DelectusIndexModule:
  version: 'v1'
DelectusTransport:
  endpoints:
    index: 'https://api.delectus.io/'
